server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/artem_db
    username: artem
    password: 5492
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: work_wear
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
  endpoint:
    health:
      show-details: always